### ISSUE TITLE
`use_relay_restrictions_maps` makes converge fail

### ISSUE THREAD

**Issue by palfrey** [chef-cookbooks/postfix#137]
(Continuing on from #135)

### Cookbook version
5.0.2

### Chef-client version
13.0.118

### Platform Details
Debian 8.4, Scaleway x64

### Scenario:
Use relay restrictions

### Steps to Reproduce:
1. Set attribute `override["postfix"]["use_relay_restrictions_maps"] = true`
2. Use recipe `postfix::server`

### Expected Result:
Working converge

### Actual Result:
```
NameError
  ---------
  undefined local variable or method `default' for cookbook: postfix, recipe: _attributes :Chef::Recipe

  Cookbook Trace:
  ---------------
    /website/config/local-mode-cache/cache/cookbooks/postfix/recipes/_attributes.rb:62:in `from_file'
    /website/config/local-mode-cache/cache/cookbooks/postfix/recipes/_common.rb:20:in `from_file'
    /website/config/local-mode-cache/cache/cookbooks/postfix/recipes/default.rb:20:in `from_file'
    /website/config/local-mode-cache/cache/cookbooks/postfix/recipes/server.rb:24:in `from_file'
    /website/config/local-mode-cache/cache/cookbooks/website/recipes/email.rb:1:in `from_file'
    /website/config/local-mode-cache/cache/cookbooks/website/recipes/default.rb:13:in `from_file'

  Relevant File Content:
  ----------------------
  /website/config/local-mode-cache/cache/cookbooks/postfix/recipes/_attributes.rb:

   55:  end
   56:
   57:  if node['postfix']['use_virtual_aliases_domains']
   58:    node.default_unless['postfix']['main']['virtual_alias_domains'] = ["#{node['postfix']['virtual_alias_domains_db_type']}:#{node['postfix']['virtual_alias_domains_db']}"]
   59:  end
   60:
   61:  if node['postfix']['use_relay_restrictions_maps']
   62>>   default['postfix']['main']['smtpd_relay_restrictions'] = "hash:#{node['postfix']['relay_restrictions_db']}, reject"
   63:  end
   64:
   65:  if node['postfix']['master']['maildrop']['active']
   66:    node.default_unless['postfix']['main']['maildrop_destination_recipient_limit'] = 1
   67:  end
   68:
   69:  if node['postfix']['master']['cyrus']['active']
   70:    node.default_unless['postfix']['main']['cyrus_destination_recipient_limit'] = 1
   71:  end
```

**Comment by palfrey** [comment]
Additional reproduction steps:
1) Apply the following patch
```
diff --git a/.kitchen.yml b/.kitchen.yml
index cd00ecf..04021e9 100644
--- a/.kitchen.yml
+++ b/.kitchen.yml
@@ -35,6 +35,9 @@ suites:
 - name: server
   run_list:
   - recipe[postfix::server]
+  attributes:
+    postfix:
+      use_relay_restrictions_maps: "yes"

 - name: sasl_auth
   run_list:
```
2. Run `kitchen converge server-debian-87`

**Comment by Coopeh** [comment]
Can confirm that I am also seeing this issue when pulling it through a wrapper cookbook. Pinned to 4.0.0 for now.
